Permissions migration script
setlife-network/trinary pull request #399
Opened 2021-04-16 13:52 UTC by sofiarm21

2021-05-07 14:28 UTC, otech47 commented on api/schema/resolvers/PermissionResolver.js
> +                        accessToken: github_access_token
Do we need to pass an access token manually?

2021-05-07 14:33 UTC, otech47 requested changes
Let's check on this again to see if we can reduce the dependency on the manual `github_access_token`

2021-05-07 15:00 UTC, otech47 requested changes
Use the github token of the owner of the Trinary Project to get permission levels and try to populate the Permissions table from that

2021-06-18 04:11 UTC, sofiarm21 commented
Too many requests are being made
contributors (106) * projects (13) + 1 project owner
<img width="1425" alt="Screen Shot 2021-06-17 at 11 54 06 PM" src="https://user-images.githubusercontent.com/49292858/122504992-6aac8780-cfc9-11eb-8d7f-fa8cdcec31fc.png">

2021-06-30 19:04 UTC, otech47 approved these changes

2021-06-30 19:04 UTC, merged