Fix Expected hours for MaxBudget contributors from Doesn't apply to amount/rate #412
setlife-network/trinary pull request #456
Opened 2021-07-14 21:54 UTC by Ovifer13

A new function was added to `selectors.js` named **estimatedHours**
This function has 2 props **amount** and **hourlyRate** and returns the division rounded of `amount/hourlyRate`.

In `ContributorTile.js` **expectedHoursMaxBudget** calls the function **estimatedHours**  to get the value and show it for the MaxBudget Contributors 

![image](https://user-images.githubusercontent.com/86666889/125697791-dbc7db37-02b8-40fe-a13c-01b9eff04bcc.png)

2021-07-16 00:19 UTC, Ovifer13 commented
closes #412

2021-07-16 15:17 UTC, otech47 requested changes

2021-07-16 15:17 UTC, otech47 commented on src/scripts/selectors.js
> +export const estimatedHours = (props) => {
Rename this to `estimateExpectedHours` or `getExpectedHours` or `calculateExpectedHours` to [utilize parts of speech](https://github.com/setlife-network/trinary/blob/develop/CONTRIBUTING.md#5-utilize-parts-of-speech)

2021-07-16 15:17 UTC, otech47 commented on src/components/ContributorTile.js
> +                amount: a.amount / 100,
To avoid floating point errors use `Number((a.amount / 100).toFixed(2))`

2021-07-16 15:17 UTC, otech47 commented on src/scripts/selectors.js
> +        Math.round(amount/parseInt(hourlyRate))
Use Number instead of parseInt

2021-07-16 15:17 UTC, otech47 commented on src/scripts/selectors.js
> +        Math.round(amount/parseInt(hourlyRate))
`Math.round(amount / parseInt(hourlyRate))`

2021-07-16 15:17 UTC, otech47 commented on src/scripts/selectors.js
> +    return(
Add space after return

`return (`

2021-07-21 16:30 UTC, otech47 approved these changes

2021-07-21 16:30 UTC, merged