Allocations with wrong inputs
setlife-network/trinary pull request #482
Opened 2021-07-26 19:57 UTC by Ovifer13

**Issue #480**

**Description:**

When creating an Allocation a user was able to input letters, negative numbers, and special characters when setting the hourly rate and expected monthly rate in prorated monthly and max budget options.

**Proof**
[Changes demostration](https://www.loom.com/share/d06fd60a2d9d4f4fbf2bf651bb3a0dbd)

2021-08-11 18:34 UTC, otech47 requested changes
I think we should refactor this and a file `/src/scripts/validation.js` and put a separate `validatePositiveNumbers` function with this logic that is repeated 3 times.

Then we can import that function and call it in each of these cases

then the validation.js file can serve as a module where we can add more validation functions where a field input needs to meet certain requirements before being passed on

2021-08-12 19:28 UTC, sofiarm21 approved these changes

2021-08-13 13:53 UTC, otech47 commented on src/scripts/validation.js
> +export const validatePositiveNumbers = (newValue, preValue) => {
NIT suggestion: `newValue, oldValue` or `nextValue, currentValue`

2021-08-13 13:53 UTC, otech47 approved these changes

2021-08-13 13:53 UTC, merged