Active/Inactive switch not working properly
setlife-network/trinary pull request #494
Opened 2021-08-12 20:27 UTC by Ovifer13

**Issue 490**
**Description**
The switch in `home` was working but it was not using the Setlife primary color when it was active.
![image](https://user-images.githubusercontent.com/86666889/129264366-9e4f47fe-a264-4cfb-835a-caa53fa373fe.png)

Also, the active/inactive switch in the edit client was not working properly.

<a href="https://www.loom.com/share/ae690fddbaf74bf6aa8f01f9bb68291b">
    <p>Project Trinary: Edit client switch fix - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/ae690fddbaf74bf6aa8f01f9bb68291b-with-play.gif">
  </a>

2021-08-13 13:25 UTC, sofiarm21 approved these changes

2021-08-19 22:13 UTC, otech47 requested changes
https://www.loom.com/share/0a6b3d96edeb4b889a6cafe86ef511b4?from_recorder=1&focus_title=1

2021-08-19 22:13 UTC, otech47 commented on src/components/InactiveClientsList.js
> +                            name='inactiveClientsCheck'
rename to `showInactiveClients`

2021-08-24 19:00 UTC, otech47 approved these changes

2021-08-24 19:00 UTC, merged