EditPayment Component
setlife-network/trinary pull request #630
Opened 2022-04-29 12:10 UTC by rishkwal

Component Details:

- [x] AddPayment component routes directly to the EditPayment component
- [x] Route: `/clients/:clientId/payments/:paymentId/update`
- [x] Allows to change details of any payment
- [x] Allows user to generate a Bitcoin invoice for the payment
- [x] Checks and displays the status of the Bitcoin invoice
- [x] Displays the checkout link for Bitcoin invoice
- [x] Cancel button sends back to `/clients/:clientId`
- [x] Add loading when `Update Payment` is clicked
- [x] Only users with `BTC` or `sats` as their currency are shown the option to view Invoice

2022-06-06 09:17 UTC, rishkwal commented
For reference: https://www.loom.com/share/7f47f68eec1942318b6b7270e49f6ab6

2022-06-15 14:52 UTC, otech47 commented on src/pages/EditPaymentPage.js
> +        const { paymentId } = this.props.match.params
NIT: combined destructure like
```
{ clientId, paymentId } = this.props.match.params
```

2022-06-15 14:56 UTC, otech47 commented on src/components/EditPaymentForm.js
> +                <BtcInvoiceModal open={openInvoice} onClose={handleCloseInvoice} bitcoinCheckoutUrl={bitcoinCheckoutUrl}/>
NIT: indent props here
```
<BtcInvoiceModal
    open={openInvoice}
    onClose={handleCloseInvoice}
    bitcoinCheckoutUrl={bitcoinCheckoutUrl}
/>
```

2022-06-15 14:58 UTC, otech47 commented on src/components/BtcInvoiceModal.js
> +                    </iframe>
NIT iframe I believe don't need a closing tag

2022-06-15 15:03 UTC, otech47 commented on src/components/AddPaymentForm.js
> +            if (errorNewPayment) {
Let's check if we can move this down to the catch clause so our error handling is cleaner/consistent

2022-06-15 15:05 UTC, otech47 requested changes
let's address the error handling cleanup and then merge

2022-06-20 08:19 UTC, merged