Update Rates data model
setlife-network/trinary pull request #656
Opened 2022-06-14 16:34 UTC by Ovifer13

**Issue #640**
- [x] Create new `roles` table with fields:
1. id
2. name -VARCHAR(255)
3. create_at - default
4. updated_at default

- [x] Add new fields to `rates` table, all fields should be **NULLABLE** and default to _NULL_
1. minimum_expected_hours - INT(11)
2. maximum_expected_hours(11)
3. minimum_hourly_rate - VARCHAR(15)
4. maximum_hourly_rate VARCHAR(15)
5. role_id - INT(11) - default to NULL

- [x] Change `total_expeted_hours` datatype to match new minimum/maximum fields in rates table
- [x] Change `hourly_rate` datatype to match new minimum/maximum fields
- [x] Anywhere in the API that `hourly_rate` and `total_expected_hours` can be provided for a Rate+Allocation, allow these new fields to be provided

2022-06-15 19:02 UTC, Ovifer13 commented
Also the API gives feedback of the new fields
![image](https://user-images.githubusercontent.com/86666889/173904596-a9de667e-0e03-4005-b03c-44c1dc644b97.png)

2022-06-20 08:48 UTC, otech47 requested changes

2022-06-20 08:48 UTC, otech47 commented on api/migrations/20220609175823-createRoles.js
> +        return queryInterface.createTable('Role', {
The table should be called `Roles` to match the pluralized naming convention of all other tables

2022-06-20 08:48 UTC, otech47 commented on api/migrations/20220609175823-createRoles.js
> +        return queryInterface.dropTable('Contributions');
Fix bad down migration that is removing the wrong table

2022-07-01 16:43 UTC, otech47 approved these changes

2022-07-01 16:43 UTC, merged