Data model changes for v2
setlife-network/trinary pull request #722
Opened 2022-11-16 08:00 UTC by rishkwal

- [x] Add `proposed_by_contributor_id` to `Allocation`
- [x] Add `status` to `Allocation`
- [x] Add `expected_budget_currency` to `Project`
- [x] Add `is_public` to `Project`
- [x] Add `project_id` to `Payment` and allow `client_id` to be `NULL`
- [x] Add `Phase` table
- [x] Add `Wallet` table

[Reference](https://www.figma.com/file/qgGWXmprU7vTv7guzWzvML/Project-Trinary)

2022-11-16 13:48 UTC, sofiaromorales commented
@rishkwal the pr seems ok but you still need to add the DB changes to the models

2022-11-16 13:51 UTC, sofiaromorales commented on api/migrations/20221110035638-addIsPrivateToProject.js
> +};
I already made this change here #720

2022-11-16 13:54 UTC, sofiaromorales requested changes

2022-11-16 13:54 UTC, sofiaromorales commented on api/models/Phase.js
> +        modelName: 'Phase',
```js
sequelize,
modelName: 'Phase',
createdAt: 'created_at',
updatedAt: 'updated_at'
```

The same applies to the other models

2022-11-16 16:01 UTC, sofiaromorales commented
@rishkwal I'm blocked by some of these changes, pls update the pr so it can be merged ASAP

2022-11-16 20:04 UTC, rishkwal commented
> @rishkwal I'm blocked by some of these changes, pls update the pr so it can be merged ASAP

@sofiaromorales I've made the changes as discussed. Let me know if I need to make any other change.

2022-11-17 00:15 UTC, sofiaromorales approved these changes

2022-11-17 00:15 UTC, merged